config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)" do
    # Skip Devise controllers we override and want to handle ourselves.
    devise_for :users, skip: [:confirmations, :registrations, :sessions, :passwords]
    devise_for :users, controllers: {
      # Add routes for Devise controllers we override and want to handle
      # ourselves here.
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations'
    }

    # Users
    # Search route must have :get and :post or will_paginate will
    # not work properly.
    match '/users/search', to: 'users#search', via: [:get, :post]
    resources :users

    get 'dashboard/index'
    post 'dashboard/start_task/:id', to: 'dashboard#start_task',
      as: :dashboard_start_task
    post 'dashboard/stop_task/:id', to: 'dashboard#stop_task',
      as: :dashboard_stop_task
    get 'dashboard/edit_note/:id', to: 'dashboard#edit_note',
      as: :dashboard_edit_note
    patch 'dashboard/update_note/:id', to: 'dashboard#update_note',
      as: :dashboard_update_note
    get 'dashboard/new_task_time', to: 'dashboard#new_task_time',
      as: :dashboard_new_task_time
    post 'dashboard/create_task_time', to: 'dashboard#create_task_time',
      as: :dashboard_create_task_time
    get 'dashboard/tasks.json', to: 'dashboard#tasks',
      as: :dashboard_tasks
    get 'dashboard/edit_duration/:id', to: 'dashboard#edit_duration',
      as: :dashboard_edit_duration
    patch 'dashboard/update_duration/:id', to: 'dashboard#update_duration',
      as: :dashboard_update_duration

    # Make sure companies routes come AFTER dashboard, as dashboard/companies
    # ajax api will route to companies/index, in error, otherwise.
    resources :companies

    resources :projects
    get 'projects/company_projects/:id', to: 'projects#company_projects',
      as: :projects_company_projects

    resources :tasks
    get 'tasks/project_tasks/:id', to: 'tasks#project_tasks',
      as: :tasks_project_tasks

    # Error handling routes
    match '/401', to: 'errors#unauthorized', via: :all, as: :unauthorized_error
    match '/404', to: 'errors#not_found', via: :all, as: :not_found_error
    match '/406', to: 'errors#not_acceptable', via: :all, as: :not_acceptable_error
    match '/500', to: 'errors#internal_server_error', via: :all, as: :internal_server_error

    root 'home#index'
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include DashboardHelper

  before_action :authenticate_user!

  def index
    @user_task_times = current_user.all_task_times
  end

  def start_task
    task_time_id = params[:id].to_i
    task_time = task_time_for_current_user(task_time_id) do |error|
      redirect_to dashboard_index_path, alert: "You cannot start this task" and return
    end

    unless task_time.start_time.nil?
      redirect_to dashboard_index_path, alert: "This task is already started"
      return
    end

    # Stop all other tasks.
    current_user.task_times.each do |t|
      force_task_stop(t) unless t.start_time.nil?
    end

    task_time.start_time = DateTime.now
    if task_time.save
      redirect_to dashboard_index_path
    else
      redirect_to dashboard_index_path, alert: "The task could not be saved."
    end
  end

  def stop_task
    task_time_id = params[:id].to_i
    task_time = task_time_for_current_user(task_time_id) do |error|
      redirect_to dashboard_index_path, alert: "You cannot stop this task" and return
    end

    if task_time.start_time.nil?
      redirect_to dashboard_index_path, alert: "This task is already stopped" and return
    end

    if force_task_stop(task_time)
      redirect_to dashboard_index_path
    else
      redirect_to dashboard_index_path, alert: "The task could not be saved."
    end
  end

  def edit_duration
    task_time_id = params[:id].to_i
    @task_time = task_time_for_current_user(task_time_id) do |error|
      redirect_to dashboard_index_path, alert: error and return
    end
  end

  def update_duration
    task_time_id = params[:id].to_i
    @task_time = task_time_for_current_user(task_time_id) do |error|
      redirect_to dashboard_index_path, alert: error and return
    end

    duration = update_duration_params[:duration]
    if duration.blank? || /[\D]+/.match?(duration)
      @task_time.errors.add(:duration, 'must be numeric')
      render :edit_duration and return
    end

    duration = duration.to_i
    @task_time.duration = duration
    @task_time.start_time = nil

    if @task_time.save
      notice = "The task has been stopped and the duration has been updated."
      redirect_to(dashboard_index_path, notice: notice)
    else
      render :edit_duration, alert: "The duration could not be updated. The task has been stopped."
    end
  end

  def edit_note
    task_time_id = params[:id].to_i
    @task_time = task_time_for_current_user(task_time_id) do |error|
      redirect_to dashboard_index_path, alert: error and return
    end
  end

  def update_note
    task_time_id = params[:id].to_i
    @task_time = task_time_for_current_user(task_time_id) do |error|
      redirect_to dashboard_index_path, alert: error and return
    end

    task_note = update_note_params[:note]
    task_note.strip!

    if params[:delete_note].present?
      task_note = nil
    else
      if task_note.blank?
        @task_time.errors.add(:note, 'is required')
        render :edit_note and return
      end
    end

    @task_time.note = task_note

    if @task_time.save
      notice = "The task note has been updated."
      redirect_to(dashboard_index_path, notice: notice)
    else
      render :edit_note
    end
  end

  def new_task_time
    @task_time = TaskTime.new
    @companies = []
    @projects = []
    @tasks = []
  end

  def create_task_time
    task_id = create_task_time_params[:tasks]
    current_user.task_times << TaskTime.create(task_id: task_id)

    if current_user.save
      redirect_to dashboard_index_path, notice: "Task time was added"
    else
      render :new_task_time, alert: "Could not save task time"
    end
  end

  def projects
    company = Company.find(params[:company_id])
    projects = company.projects unless company.nil?
    respond_to do |format|
      format.json do
        message = projects.present? ? "" : "There are no projects for this company"
        status = projects.present? ? :ok : :not_found
        render json: { response: projects, status: status, message: message }
      end
    end
  end

  def tasks
    task_times = current_user.task_times

    rejected_tasks = task_times.map { |t| t.task.id }
    rejected_tasks = rejected_tasks.split(',').join(',') unless rejected_tasks.empty?

    project = Project.find(params[:project_id])

    tasks = rejected_tasks.present? ?
      project.tasks.where("id not in (#{rejected_tasks})").
                          select([:id, :name]).
                          order(:name) :
                          project.tasks.select([:id, :name]).order(:name)

    tasks = tasks.present? ? tasks : []
    respond_to do |format|
      format.json do
        message = tasks.present? ? "" :
          "There are no tasks for this project or...\n\n"\
          "you already have all tasks for this project associated with you."
        status = tasks.present? ? :ok : :not_found
        render json: { response: tasks, status: status, message: message }
      end
    end
  end

  protected

  def create_task_time_params
    params.permit(:companies, :projects, :tasks)
  end

  def update_note_params
    params.require(:task_time).permit(:note)
  end

  def update_duration_params
    params.require(:task_time).permit(:duration)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def task_time_for_current_user(task_time_id)
    task_time = TaskTime.find(task_time_id)
    return task_time unless task_time.nil? || task_time.user_id != current_user.id
    yield "The Task Time is not associated with you"
  rescue ActiveRecord::RecordNotFound
    yield "The Task Time could not be found"
  end

  def force_task_stop(task_times)
    start_time = task_times.start_time
    duration = task_times.duration || 0
    duration += ((DateTime.now - DateTime.parse(start_time.to_s(:rfc822))) * 24 * 60 * 60).to_i
    task_times.duration = duration
    task_times.start_time = nil
    task_times.save
  end
end

app/views/dashboard/edit_duration.html.erb
<% content_for :title do %>Edit Duration<% end %>
<div class="page-header">
  <h1>Task Duration</h1>
</div>

<%= render partial: 'shared/errors', locals: { resource: @task_time, i18n_key: 'errors.messages.not_saved', i18n_args: nil } %>

<%= form_with(model: @task_time, url: dashboard_update_duration_path, local: true) do |f| %>
  <div class="form-group">
    <div class='input-md'><%= f.label 'Company' %></div>
    <div class='input-md'><%= @task_time.task.project.company.name %></div>
  </div>
  <div class="form-group">
    <div class='input-md'><%= f.label 'Project' %></div>
    <div class='input-md'><%= @task_time.task.project.name %></div>
  </div>
  <div class="form-group">
    <div class='input-md'><%= f.label 'Task' %></div>
    <div class='input-md'><%= @task_time.task.name %></div>
  </div>
  <div class="form-group">
    <div class='input-md'><%= f.label :duration %></div>
    <div class='input-md'><%= f.text_field :duration, class: "form-control" %></div>
  </div>

  <div class='actions form-group'>
    <div class='input-md'>
      <%= submit_tag 'Save Duation', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', dashboard_index_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/dashboard/edit_note.html.erb
<% content_for :title do %>New Task Note<% end %>
<div class="page-header">
  <h1>Task Note</h1>
</div>

<%= render partial: 'shared/errors', locals: { resource: @task_time, i18n_key: 'errors.messages.not_saved', i18n_args: nil } %>

<%= form_with(model: @task_time, url: dashboard_update_note_path, local: true) do |f| %>
  <div class="form-group">
    <div class='input-md'><%= f.label 'Company' %></div>
    <div class='input-md'><%= @task_time.task.project.company.name %></div>
  </div>
  <div class="form-group">
    <div class='input-md'><%= f.label 'Project' %></div>
    <div class='input-md'><%= @task_time.task.project.name %></div>
  </div>
  <div class="form-group">
    <div class='input-md'><%= f.label 'Task' %></div>
    <div class='input-md'><%= @task_time.task.name %></div>
  </div>
  <div class="form-group">
    <div class='input-md'><%= f.label :note %></div>
    <div class='input-md'><%= f.text_field :note, class: "form-control" %></div>
  </div>

  <div class='actions form-group'>
    <div class='input-md'>
      <%= submit_tag 'Save Note', class: 'btn btn-primary' %>
      <%= submit_tag 'Delete Note', class: 'btn btn-delete', name: :delete_note unless @task_time.note.blank? %>
      <%= link_to 'Cancel', dashboard_index_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/dashboard/index.html.erb
<% content_for :title do %>Dashboard<% end %>
<div class="page-header">
  <h1>Dashboard</h1>
</div>

<div class="_container">
  <div class="row">
    <div class="col-md-12 clearfix">
      <div class="pull-left" style="padding-right:10px;">
        <h2>Tasks</h2>
      </div>
      <div style="margin-top:25px;">
        <%= link_to "Add Task",
          dashboard_new_task_time_path,
          class: 'btn btn-primary btn-xs' %>
      </div>
    </div>
  </div>
</div>

<div style="margin-top: 12px;">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Company</th>
        <th>Project</th>
        <th>Task</th>
        <th>Duration</th>
        <th>Notes</th>
      </tr>
    </thead>
    <tbody>
      <% @user_task_times.each do |task| %>
        <% task_status_css = "task-started" if task.started?  %>
        <tr class="<%= task_status_css %>">
          <td><%= task.company_name %></td>
          <td><%= task.project_name %></td>
          <td>
            <% if task.stopped? %>
              <div class="pull-left" style="margin-right:5px;">
                <%= button_to "Start",
                  dashboard_start_task_path(id: task.task_time_id),
                  class: 'btn btn-success btn-xs' %>
              </div>
            <% else %>
              <div class="pull-left" style="margin-right:5px;">
                <%= button_to "Stop",
                    dashboard_stop_task_path(id: task.task_time_id),
                    class: 'btn btn-stop btn-xs' %>
              </div>
            <% end %>
            <%= task.task_name %>
          </td>
          <td>
            <div class="pull-left" style="margin-right:5px;">
              <%= link_to "Edit",
                dashboard_edit_duration_path(task.task_time_id),
                class: 'btn btn-primary btn-xs' %>
            </div>
            <span class="<%= 'started' if task.started?  %>"><%= task.task_duration %></span> seconds
          </td>
          <td style="max-width: 200px;">
            <table>
              <row>
                  <td style="vertical-align:top; padding-right: 5px;">
                    <%= link_to task.task_time_note.blank? ? "Add Note" : "Edit Note",
                      dashboard_edit_note_path(task.task_time_id),
                      class: 'btn btn-primary btn-xs pull-left' %>
                  </td>
                  <td style="vertical-align:top;">
                    <% unless task.task_time_note.blank? %>
                      <%= task.task_time_note %>
                    <% end %>
                </td>
              </row>
            </table>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= content_for :javascripts do %>
  <script>
  </script>
<% end %>

app/views/dashboard/new_task_time.html.erb
<% content_for :title do %>Add Task Time<% end %>
<div class="page-header">
  <h1>Add Task Time</h1>
</div>

<%= render partial: 'shared/errors', locals: { resource: @task_time, i18n_key: 'errors.messages.not_saved', i18n_args: nil } %>

<%= form_with(scope: :task_time, url: dashboard_create_task_time_path, local: true) do |f| %>
  <div class="form-group">
    <div class='input-md'><%= f.label 'Company' %></div>
    <div class='input-md'>
      <%= select_tag "companies",
             options_from_collection_for_select(@companies, "id", "name"),
             { onchange: "companies_onchange(this);", class: "select-min-width" } %>
    </div>
  </div>
  <div class="form-group">
    <div class='input-md'><%= f.label 'Project' %></div>
    <div class='input-md'>
      <%= select_tag "projects",
            options_from_collection_for_select(@projects, "id", "name"),
            { onchange: "projects_onchange(this);", class: "select-min-width" } %>
    </div>
  </div>
  <div class="form-group">
    <div class='input-md'><%= f.label 'Task' %></div>
    <div class='input-md'>
      <%= select_tag "tasks",
            options_from_collection_for_select(@tasks, "id", "name"),
            { onchange: "tasks_onchange(this);", class: "select-min-width" } %>
    </div>
  </div>

  <div class='actions form-group'>
    <div class='input-md'>
      <%= submit_tag 'Save', id: :submit_button, class: 'btn btn-primary' %>
      <%= link_to 'Cancel', dashboard_index_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

<% content_for :javascripts do %>
  <script>
    $(function() {
      initSelect("companies");
      initSelect("projects");
      initSelect("tasks");

      enableSubmitButton(false);

      $.ajax({
        url: "<%= companies_path %>",
        success: function(data, textStatus, jqXHR) {
          if (guardData(data)) {
            enableControl("companies", true);
            addItemsTo("companies", data["response"]);
          }
        },
        error: function(jqXHR, textStatus, errorThrown) {
          alert("AJAX Error:" + textStatus);
        }
      });
    });

    function companies_onchange(selectElement) {
      initSelect("projects");
      initSelect("tasks");
      enableSubmitButton(false);
      if (!isValidSelection(selectElement)) {
        return;
      }
      let companyId = getSelectedValueFor(selectElement);
      let url = "<%= projects_company_projects_path(0).gsub(/0/, '') %>";
      $.ajax({
        url: url + companyId,
        success: function(data, textStatus, jqXHR) {
          if (guardData(data)) {
            enableControl("projects", true);
            addItemsTo("projects", data["response"]);
          }
        },
        error: function(jqXHR, textStatus, errorThrown) {
          alert("AJAX Error:" + textStatus);
        }
      });
    };

    function projects_onchange(selectElement) {
      initSelect("tasks");
      enableSubmitButton(false);
      if (!isValidSelection(selectElement)) {
        return;
      }
      let projectId = getSelectedValueFor(selectElement);
      $.ajax({
        url: "/dashboard/tasks.json?project_id=" + projectId,
        success: function(data, textStatus, jqXHR) {
          if (guardData(data)) {
            enableControl("tasks", true)
            addItemsTo("tasks", data["response"]);
          }
        },
        error: function(jqXHR, textStatus, errorThrown) {
          alert("AJAX Error:" + textStatus);
        }
      });
    };

    function tasks_onchange(selectElement) {
      enableSubmitButton(isValidSelection(selectElement));
    };

    function guardData(data) {
      json = data["response"];
      status = data["status"];
      if (status != "ok") {
        alert(data["message"]);
        return false;
      }
      return true;
    };

    function addItemsTo(selectId, json) {
      let $select = $('#' + selectId);
      $.each(json, function (i, item) {
        $select.append(
          $('<option>', { value: item.id, text: item.name })
        );
      });
    };

    function getSelectedValueFor(selectElement) {
      let selected = selectElement.options[selectElement.selectedIndex];
      return selected.value;
    };

    function isValidSelection(selectElement) {
      return getSelectedValueFor(selectElement) > 0;
    };

    function enableSubmitButton(enable) {
      enableControl("submit_button", enable);
    };

    function enableControl(elementId, enable) {
      $("#" + elementId).prop("disabled", !enable);
    };

    function initSelect(selectId) {
      let $select = $("#" + selectId)
      $select.find("option").remove();
      $select.append($('<option>', { value: 0, text: "--- Select --- " }));
      enableControl(selectId, false);
    }
  </script>
<% end %>