config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)" do
    # Skip Devise controllers we override and want to handle ourselves.
    devise_for :users, skip: [:confirmations, :registrations, :sessions, :passwords]
    devise_for :users, controllers: {
      # Add routes for Devise controllers we override and want to handle
      # ourselves here.
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations'
    }

    # Users
    # Search route must have :get and :post or will_paginate will
    # not work properly.
    match '/users/search', to: 'users#search', via: [:get, :post]
    resources :users

    get 'dashboard/index'
    post 'dashboard/start_task/:id', to: 'dashboard#start_task',
      as: :dashboard_start_task
    post 'dashboard/stop_task/:id', to: 'dashboard#stop_task',
      as: :dashboard_stop_task
    get 'dashboard/edit_note/:id', to: 'dashboard#edit_note',
      as: :dashboard_edit_note
    patch 'dashboard/update_note/:id', to: 'dashboard#update_note',
      as: :dashboard_update_note
    get 'dashboard/new_task_time', to: 'dashboard#new_task_time',
      as: :dashboard_new_task_time
    post 'dashboard/create_task_time', to: 'dashboard#create_task_time',
      as: :dashboard_create_task_time
    get 'dashboard/tasks.json', to: 'dashboard#tasks',
      as: :dashboard_tasks
    get 'dashboard/edit_duration/:id', to: 'dashboard#edit_duration',
      as: :dashboard_edit_duration
    patch 'dashboard/update_duration/:id', to: 'dashboard#update_duration',
      as: :dashboard_update_duration

    # Make sure companies routes come AFTER dashboard, as dashboard/companies
    # ajax api will route to companies/index, in error, otherwise.
    resources :companies

    resources :projects
    get 'projects/company_projects/:id', to: 'projects#company_projects',
      as: :projects_company_projects

    resources :tasks
    get 'tasks/project_tasks/:id', to: 'tasks#project_tasks',
      as: :tasks_project_tasks

    # Error handling routes
    match '/401', to: 'errors#unauthorized', via: :all, as: :unauthorized_error
    match '/404', to: 'errors#not_found', via: :all, as: :not_found_error
    match '/406', to: 'errors#not_acceptable', via: :all, as: :not_acceptable_error
    match '/500', to: 'errors#internal_server_error', via: :all, as: :internal_server_error

    root 'home#index'
  end

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  has_many :task_times, dependent: :delete_all

  scope :order_by_company_project_and_task, -> {
    joins(project: :company).order('companies.name, projects.name, tasks.name')
  }

  validates_presence_of :name
  validates_uniqueness_of :name, scope: :project_id
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_user, except: [:index, :project_tasks]
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.order_by_company_project_and_task.paginate(page: params[:page] || 1, per_page: helpers.pager_per_page)
    respond_to do |format|
      message = @tasks.present? ? "" : "There are no tasks available at this time"
      format.json do
        status = @tasks.present? ? :ok : :not_found
        render json: { response: @tasks, status: status, message: message }
      end
      format.html do
        # Only authorize html format, json is okay because we use it as
        # an api.
        authorize(:task)
        flash[:alert] = message unless message.blank?
        @tasks
      end
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: tasks_path }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_path, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: tasks_path }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def project_tasks
=begin
    company = Company.find_by(id: params[:id])
    @projects = company.nil? ? Project.none : company.projects
    @projects = @projects.order_by_company_and_project
    respond_to do |format|
      message = @projects.present? ? "" : "There are no projects available for this company at this time"
      format.json do
        status = @projects.present? ? :ok : :not_found
        render json: { response: @projects, status: status, message: message }
      end
      format.html do
        # Only authorize html format, json is okay because we use it as
        # an api.
        authorize(:project)
        flash[:alert] = message unless message.blank?
        @projects
      end
    end
=end
  end

  private

    def authorize_user
      authorize(:task)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :project_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_delete_task_link_to.html.erb
<% destroy_text = t('.destroy', default: t("helpers.links.destroy")) %>
<%
button_size ||= :medium
button_css_class =
case
when button_size == :large
  'btn-lg'
when button_size == :small
  'btn-xs'
else
  'btn-md'
end
%>
<%= link_to task_path(task), {
      method: :delete,
      class: "btn btn-delete-task #{button_css_class}",
      style: 'padding: 6px 12px;',
      title: "#{destroy_text}",
      data: {
        dialog_title: "#{destroy_text} this task?",
        entity_name: "task <strong>#{task.name}</strong>",
        warning: "<span style='color:#c00;'>Warning: All user associated Task Times will be deleted!</span>"
      },
      form: { style: 'display:inline-block;' }
    } do %>
    <%= destroy_text %>
<% end %>

app/views/tasks/_form.html.erb
<%= render partial: 'shared/errors', locals: { resource: @task, i18n_key: 'errors.messages.not_saved', i18n_args: nil } %>

<%= form_with(model: @task, local: true) do |f| %>
  <div class="form-group">
    <div class='input-md'><%= f.label 'Company' %></div>
    <div class='input-md'><%= @task.project.company.name %></div>
  </div>

  <div class="form-group">
    <div class='input-md'><%= f.label 'Project' %></div>
    <div class='input-md'><%= @task.project.name %></div>
  </div>

  <div class="form-group">
    <div class='input-md'><%= f.label 'Task name' %></div>
    <div class='input-md'><%= f.text_field :name, class: "form-control" %></div>
  </div>

  <div class='actions form-group'>
    <div class='input-md'>
      <%= submit_tag 'Save', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', tasks_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<% content_for :title do %>Tasks<% end %>

<div class="_container">
  <div class="row">
    <div class="col-md-12 clearfix">
      <div class="pull-left" style="padding-right:10px;">
        <h1>Tasks</h1>
      </div>
      <div style="margin-top:25px;">
        <%= link_to "Add Task",
          new_task_path,
          class: 'btn btn-primary btn-sx' %>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'shared/pager', locals: { resource: @tasks } %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Company</th>
      <th>Project</th>
      <th>Task</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td style="width:20%"><%= task.project.company.name %></td>
        <td style="width:20%"><%= task.project.name %></td>
        <td style="width:40%"><%= task.name %></td>
        <td>
          <%= link_to t('.show', default: t("helpers.links.show")),
                      task_path(task), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', default: t("helpers.links.edit")),
                      edit_task_path(task), :class => 'btn btn-default btn-xs' %>
          <%= render partial: 'delete_task_link_to', locals: { task: task, button_size: :small } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render partial: 'shared/pager', locals: { resource: @tasks } %>

app/views/tasks/new.html.erb
<% content_for :title do %>Add Task<% end %>
<div class="page-header">
  <h1>Add Task</h1>
</div>

<%= render partial: 'shared/errors', locals: { resource: @task, i18n_key: 'errors.messages.not_saved', i18n_args: nil } %>

<%= form_with(scope: :task, url: tasks_path, local: true) do |f| %>
  <div class="form-group">
    <div class='input-md'><%= f.label 'Company' %></div>
    <div class='input-md'>
      <%= select_tag("company_id", nil, {
            prompt: "--- Select ---",
            onchange: "companies_onchange(this);",
            class: "select-min-width" }) %>
    </div>
  </div>

  <div class="form-group">
    <div class='input-md'><%= f.label 'Project' %></div>
    <div class='input-md'>
      <%= select_tag("task[project_id]", nil, {
            prompt: "--- Select ---",
            onchange: "projects_onchange(this);",
            class: "select-min-width" }) %>
    </div>
  </div>

  <div class="form-group">
    <div class='input-md'><%= f.label :name %></div>
    <div class='input-md'><%= f.text_field :name, id: :task_name, class: "form-control" %></div>
  </div>

  <div class='actions form-group'>
    <div class='input-md'>
      <%= submit_tag 'Save', id: :submit_button, class: 'btn btn-primary' %>
      <%= link_to 'Cancel', tasks_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

<% content_for :javascripts do %>
  <script>
    let selectedCompanyId = "<%= @task.project.nil? ? 0 : @task.project.company_id %>";
    let selectedProjectId = "<%= @task.project_id.nil? ? 0 : @task.project_id %>";

    let selectElementIdForCompany = "company_id";
    let selectElementIdForProject = "task_project_id";
    let textInputElementIdForTaskName = "task_name";

    $(function() {
      initSelect(selectElementIdForCompany);
      initSelect(selectElementIdForProject);

      enableSubmitButton(textInputElementIdForTaskName, selectedCompanyId > 0 && selectedProjectId > 0);
      enableControl(textInputElementIdForTaskName, selectedCompanyId > 0 && selectedProjectId > 0);

      let url = "<%= companies_path %>";
      loadSelectFrom(url, null, selectElementIdForCompany, selectedCompanyId);

      if (selectedCompanyId > 0) {
        let url = "<%= projects_company_projects_path(0).gsub(/0/, '') %>";
        loadSelectFrom(url, selectedCompanyId, selectElementIdForProject, selectedProjectId);
      }
    });

    function companies_onchange(selectElement) {
      enableSubmitButton(false);
      enableControl(textInputElementIdForTaskName, false);
      initSelect(selectElementIdForProject);
      $("#" + textInputElementIdForTaskName).val("");
      if (!isValidSelection(selectElement)) {
        return;
      }
      let companyId = getSelectedValueFor(selectElement);
      let url = "<%= projects_company_projects_path(0).gsub(/0/, '') %>";
      loadSelectFrom(url, companyId, selectElementIdForProject, selectedProjectId);
    };

    function projects_onchange(selectElement) {
      enableSubmitButton(false);
      enableControl(textInputElementIdForTaskName, false);
      $("#" + textInputElementIdForTaskName).val("");
      if (!isValidSelection(selectElement)) {
        return;
      }
      enableSubmitButton(true);
      enableControl(textInputElementIdForTaskName, true);
    };

    function loadSelectFrom(url, urlParams, selectId, selectedOptionValue) {
      $.ajax({
        url: urlParams == null ? url : url + urlParams,
        success: function(data, textStatus, jqXHR) {
          if (guardData(data)) {
            enableControl(selectId, true);
            addItemsTo(selectId, selectedOptionValue, data["response"]);
          }
        },
        error: function(jqXHR, textStatus, errorThrown) {
          alert("AJAX Error:" + textStatus);
        }
      });
    };

    function guardData(data) {
      json = data["response"];
      status = data["status"];
      if (status != "ok") {
        alert(data["message"]);
        return false;
      }
      return true;
    };

    function addItemsTo(selectId, selectedValue, json) {
      let $select = $('#' + selectId);
      $.each(json, function (i, item) {
        let option = $('<option>', { value: item.id, text: item.name });
        if (item.id == selectedValue) {
          option.attr('selected', 'selected');
        }
        $select.append(option);
      });
    };

    function getSelectedValueFor(selectElement) {
      let selected = selectElement.options[selectElement.selectedIndex];
      return selected.value;
    };

    function isValidSelection(selectElement) {
      return getSelectedValueFor(selectElement) > 0;
    };

    function enableSubmitButton(enable) {
      enableControl("submit_button", enable);
    };

    function enableControl(elementId, enable) {
      $("#" + elementId).prop("disabled", !enable);
    };

    function initSelect(selectId) {
      let $select = $("#" + selectId)
      $select.find("option").remove();
      $select.append($('<option>', { value: 0, text: "--- Select ---" }));
      enableControl(selectId, false);
    }
  </script>
<% end %>

app/views/tasks/show.html.erb
<% content_for :title do %>Task<% end %>
<div class="page-header">
  <h1>Task</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Company:</strong></dt><dd><%= @task.project.company.name %></dd>
  <dt><strong>Project:</strong></dt><dd><%= @task.project.name %></dd>
  <dt><strong>Task name:</strong></dt><dd><%= @task.name %></dd>
  <dt><strong>Created at:</strong></dt><dd><%= @task.created_at %></dd>
</dl>

<%= link_to t('.back', default: t("helpers.links.back")),
              tasks_path, class: 'btn btn-default'  %>
<%= link_to t('.edit', default: t("helpers.links.edit")),
              edit_task_path(@task), class: 'btn btn-default' %>
<%= render partial: 'delete_task_link_to', locals: { task: @task, button_size: :medium } %>