config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)" do
    # Skip Devise controllers we override and want to handle ourselves.
    devise_for :users, skip: [:confirmations, :registrations, :sessions, :passwords]
    devise_for :users, controllers: {
      # Add routes for Devise controllers we override and want to handle
      # ourselves here.
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations'
    }

    # Users
    # Search route must have :get and :post or will_paginate will
    # not work properly.
    match '/users/search', to: 'users#search', via: [:get, :post]
    resources :users

    get 'dashboard/index'
    post 'dashboard/start_task/:id', to: 'dashboard#start_task',
      as: :dashboard_start_task
    post 'dashboard/stop_task/:id', to: 'dashboard#stop_task',
      as: :dashboard_stop_task
    get 'dashboard/edit_note/:id', to: 'dashboard#edit_note',
      as: :dashboard_edit_note
    patch 'dashboard/update_note/:id', to: 'dashboard#update_note',
      as: :dashboard_update_note
    get 'dashboard/new_task_time', to: 'dashboard#new_task_time',
      as: :dashboard_new_task_time
    post 'dashboard/create_task_time', to: 'dashboard#create_task_time',
      as: :dashboard_create_task_time
    get 'dashboard/tasks.json', to: 'dashboard#tasks',
      as: :dashboard_tasks
    get 'dashboard/edit_duration/:id', to: 'dashboard#edit_duration',
      as: :dashboard_edit_duration
    patch 'dashboard/update_duration/:id', to: 'dashboard#update_duration',
      as: :dashboard_update_duration

    # Make sure companies routes come AFTER dashboard, as dashboard/companies
    # ajax api will route to companies/index, in error, otherwise.
    resources :companies

    resources :projects
    get 'projects/company_projects/:id', to: 'projects#company_projects',
      as: :projects_company_projects

    resources :tasks
    get 'tasks/project_tasks/:id', to: 'tasks#project_tasks',
      as: :tasks_project_tasks

    # Error handling routes
    match '/401', to: 'errors#unauthorized', via: :all, as: :unauthorized_error
    match '/404', to: 'errors#not_found', via: :all, as: :not_found_error
    match '/406', to: 'errors#not_acceptable', via: :all, as: :not_acceptable_error
    match '/500', to: 'errors#internal_server_error', via: :all, as: :internal_server_error

    root 'home#index'
  end

end

app/models/user.rb
class User < ApplicationRecord
  include RoleNames

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, email: true
  validates :user_name, user_name: true
  #validates :name, length: { minimum: 3, maximum: 32,
  #  too_long: "Name must be less than or equal to %{count} characters" }, allow_blank: true

  has_many :user_roles, dependent: :delete_all
  has_many :roles, through: :user_roles

  has_many :task_times, dependent: :delete_all

  scope :admins, -> { joins(:roles).where("roles.name = '#{ADMIN_ROLE_NAME}'") }
  scope :non_admins, -> {
    where.not(id: User.joins(:roles).select(:id).where("roles.name = '#{ADMIN_ROLE_NAME}'")) }

  # TODO: Move this to helper and change params to UserSearchCriteria param.
  def self.find_by_search_criteria_with_paginate(search_option, search_string, paginate_params = { page: nil, per_page: nil }, user = nil)
    users = find_by_search_criteria(search_option, search_string, user)
    users = users.paginate(page: paginate_params[:page], per_page: paginate_params[:per_page])
  end

  # TODO: Move this to helper and change params to UserSearchCriteria param.
  def self.find_by_search_criteria(search_option, search_string, user = nil)
    return User.none unless search_option.presence && search_string.presence
    # search_option must be a valid, whitelisted column on the users table.
    raise ArgumentError unless ['email', 'user_name'].include?(search_option)
    User.where("users.#{search_option} ILIKE ?", "%#{search_string}%")
  end

  # Is the user in the user role?
  def user?
    role?(:user)
  end

  # Is the user in the admin role?
  def admin?
    role?(:admin)
  end

  # Returns true if the user is in role.
  def role?(role)
    return false if role.blank? || self.roles.count == 0
    return false unless role.is_a?(String) || role.is_a?(Symbol)
    role = role.to_s if role.is_a?(Symbol)
    self.roles.exists?(name: role.downcase)
  end

  def all_task_times
    query = <<-SQL
      select distinct
        company.name,
        project.name,
        task.name,
        task_time.duration,
        task_time.id,
        task_time.note,
        task_time.start_time
        from users as "user"
        join task_times task_time on task_time.user_id = "user".id
        join tasks task on task.id = task_time.task_id
        join projects project on project.id = task.project_id
        join companies company on company.id = project.company_id
        where "user".id = #{self.id}
        order by company.name, project.name, task.name
    SQL

    user_task_times_array = []

    ActiveRecord::Base.connection.execute(query).values.each do |e|
      user_task_times_array <<
        UserTaskTimes.new(
          e[0], # Company
          e[1], # Project
          e[2], # Task name
          e[3].to_i, # Duration
          e[4].to_i, # Task time id
          e[5], # Task time note
          e[6].present?) # Task time started
    end

    user_task_times_array
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  layout "users/default"
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  #def after_confirmation_path_for(resource_name, resource)
  #  super(resource_name, resource)
  #end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  layout "users/default"
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation])
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout "users/default"
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password, :remember_me])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :authorize_user

  # A frequent practice is to place the standard CRUD actions in each controlle
  # in the following order: index, show, new, edit, create, update and destroy.

  def index
    @search_criteria = create_initial_search_criteria
  end

  def search
    paginate_params = { page: params[:page].presence || 1, per_page: params[:per_page] }
    @search_criteria = UsersSearchCriteria.new(search_params.merge(paginate_params))
    render :index
  end

  def show
    begin
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      # TODO: logging
      redirect_to(users_path, notice: "The user could not be found.")
    end
  end

  def new
    @user = User.new
  end

  def edit
    begin
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      # TODO: logging
      redirect_to(users_path, notice: "The user could not be found. The user could not be edited.")
    end
  end

  def update
    begin
      @user = User.find(params[:id])
      if @user.update(user_params)
        notice = "The user's email has been updated, and a confirmation email has been sent."
        redirect_to(users_path, notice: notice)
      else
        render :edit
      end
    rescue ActiveRecord::RecordNotFound
      # TODO: logging
      redirect_to(users_path, notice: "The user could not be found. The update failed.")
    end
  end

  def destroy
    begin
      @user = User.find(params[:id])
      @user.destroy
      redirect_to users_path, notice: "User #{@user.email} has been deleted"
      return
    rescue ActiveRecord::RecordNotFound
      # TODO: logging
      redirect_to(users_path, notice: "The user could not be found. The delete failed.")
    end
  end

  private

  def authorize_user
    authorize(:user)
  end

  def user_params
    params.require(:user).permit(:email, :user_name)
    # Use this when we add user_name, etc.
    # params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
  end

  def search_params
    params.require(:users_search_criteria).permit(:search_string, :search_option)
  end

  def create_initial_search_criteria
    paginate_params = { page: params[:page].presence || 1, per_page: params[:per_page] }
    UsersSearchCriteria.new({ search_string: "", search_option: "show_all" }.merge(paginate_params))
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/dashboard.html.erb
<% content_for :title do %>Dashboard<% end %>

<h1>Dashboard</h1>

<%= render partial: 'shared/user_tasks' %>

app/views/users/edit.html.erb
<% content_for :title do %>Edit User<% end %>
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<%= render partial: 'shared/errors', locals: { resource: @user, i18n_key: 'errors.messages.not_saved', i18n_args: nil } %>

<%= form_with(model: @user, local: true) do |f| %>
  <div class="form-group">
    <div class='input-md'><%= f.label :user_name %></div>
    <div class='input-md'><%= f.text_field :user_name, class: "form-control" %></div>
  </div>

  <div class="form-group">
    <div class='input-md'><%= f.label :email %></div>
    <div class='input-md'><%= f.email_field :email, class: "form-control", autocomplete: "email" %></div>
  </div>

  <div class='actions form-group'>
    <div class='input-md'>
      <%= submit_tag 'Save', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', users_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%= translate('.title',
            default: model_class.model_name.human.pluralize.titleize) %></h1>
</div>

<% if @search_criteria.errors.any? %>
  <%= ResourceMessageBuilder.build_html_errors(@search_criteria, 'errors.messages.search_failed',
       resource: @search_criteria.class.model_name.human.downcase) %>
<% end %>
<%# Note: This form MUST use method :get or will_paginate will not paginate properly! %>
<%= form_with(model: @search_criteria, id: :search_criteria_form, url: users_search_path, method: :get, local: true) do |f| %>
  <div class="row">
    <div class="col-lg-12">
      <div class="input-group">
        <span id="selected_search_option" class="input-group-addon input-group-addon-primary"></span>
        <%= f.hidden_field(:search_option, id: :search_option) %>
        <%= f.text_field :search_string, id: :search_string, placeholder: '', class: 'form-control' %>

        <div class="input-group-btn">
          <button id="search_button" type="button" class="btn btn-primary"><i class='fa fa-search fa-md'>&nbsp;</i>Search</button>
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <ul id="search_options" class="dropdown-menu dropdown-menu-right">
            <li><a href="#">Search by...</a></li>
            <li role="separator" class="divider"></li>
            <li><a id="show_all" class="search-item" data-placeholder="" href="#">Show all</a></li>
            <li><a id="email" class="search-item" data-placeholder="e.g. email@gmail.com" href="#">Email</a></li>
            <li><a id="user_name" class="search-item" data-placeholder="e.g. user_name" href="#">User name</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class='row' style="margin-top:15px;">
    <div class="col-lg-12">
      <%= render partial: 'shared/pager', object: @search_criteria.users, as: :resource %>
    </div>
  </div>

  <%= render partial: 'users/shared/users', locals: { users: @search_criteria.users }%>

  <div class='row'>
    <div class="col-lg-12">
      <%= render partial: 'shared/pager', object: @search_criteria.users, as: :resource %>
    </div>
  </div>

<% end %>

<% content_for :javascripts do %>
  <%= javascript_include_tag 'delete-link-button' %>
<% end %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<%= render partial: 'shared/errors', locals: { resource: @user, i18n_key: 'errors.messages.not_saved', i18n_args: nil } %>

<%= form_with(model: @user, local: true) do |f| %>
  <div class="form-group">
    <div class='input-md'><%= f.label :user_name %></div>
    <div class='input-md'><%= f.text_field :user_name, class: "form-control", autofocus: true, autocomplete: "off" %></div>
  </div>

  <div class="form-group">
    <div class='input-md'><%= f.label :email %></div>
    <div class='input-md'><%= f.email_field :email, class: "form-control", autocomplete: "email" %></div>
  </div>

  <div class="form-group">
    <div class='input-md'><%= f.label :password %></div>
    <div class='input-md'><%= f.password_field :password, class: "form-control", autocomplete: "off" %></div>
  </div>

  <div class="form-group">
    <div class='input-md'><%= f.label :confirm_password %></div>
    <div class='input-md'><%= f.password_field :confirm_password, class: "form-control", autocomplete: "off" %></div>
  </div>

  <div class='actions form-group'>
    <div class='input-md'>
      <%= submit_tag 'Update user', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', users_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Email:</strong></dt><dd><%= @user.email %></dd>
  <dt><strong>User name:</strong></dt><dd><%= @user.user_name %></dd>
  <dt><strong>Last logged in:</strong></dt><dd><%= @user.last_sign_in_at %></dd>
  <dt><strong>Confirmed on:</strong></dt><dd><%= @user.confirmed_at %></dd>
  <dt><strong>Confirmation sent on:</strong></dt><dd><%= @user.confirmation_sent_at %></dd>
  <dt><strong>Unconfirmed email:</strong></dt>
  <dd><%= @user.unconfirmed_email %></dd>
</dl>

<%= link_to t('.back', default: t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', default: t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<% destroy_text = t('.destroy', default: t("helpers.links.destroy")) %>
<%= link_to user_path(@user), {
      method: :delete,
      class: 'btn btn-xs btn-danger',
      style: 'padding: 6px 12px;',
      title: "#{destroy_text}",
      data: {
        dialog_title: "#{destroy_text} this user?",
        user_email: "#{@user.email}"
      },
      form: { style: 'display:inline-block;' }
    } do %>
    <%= destroy_text %>
<% end %>