config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)" do
    # Skip Devise controllers we override and want to handle ourselves.
    devise_for :users, skip: [:confirmations, :registrations, :sessions, :passwords]
    devise_for :users, controllers: {
      # Add routes for Devise controllers we override and want to handle
      # ourselves here.
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations'
    }

    # Users
    # Search route must have :get and :post or will_paginate will
    # not work properly.
    match '/users/search', to: 'users#search', via: [:get, :post]
    resources :users

    get 'dashboard/index'
    post 'dashboard/start_task/:id', to: 'dashboard#start_task',
      as: :dashboard_start_task
    post 'dashboard/stop_task/:id', to: 'dashboard#stop_task',
      as: :dashboard_stop_task
    get 'dashboard/edit_note/:id', to: 'dashboard#edit_note',
      as: :dashboard_edit_note
    patch 'dashboard/update_note/:id', to: 'dashboard#update_note',
      as: :dashboard_update_note
    get 'dashboard/new_task_time', to: 'dashboard#new_task_time',
      as: :dashboard_new_task_time
    post 'dashboard/create_task_time', to: 'dashboard#create_task_time',
      as: :dashboard_create_task_time
    get 'dashboard/tasks.json', to: 'dashboard#tasks',
      as: :dashboard_tasks
    get 'dashboard/edit_duration/:id', to: 'dashboard#edit_duration',
      as: :dashboard_edit_duration
    patch 'dashboard/update_duration/:id', to: 'dashboard#update_duration',
      as: :dashboard_update_duration

    # Make sure companies routes come AFTER dashboard, as dashboard/companies
    # ajax api will route to companies/index, in error, otherwise.
    resources :companies

    resources :projects
    get 'projects/company_projects/:id', to: 'projects#company_projects',
      as: :projects_company_projects

    resources :tasks
    get 'tasks/project_tasks/:id', to: 'tasks#project_tasks',
      as: :tasks_project_tasks

    # Error handling routes
    match '/401', to: 'errors#unauthorized', via: :all, as: :unauthorized_error
    match '/404', to: 'errors#not_found', via: :all, as: :not_found_error
    match '/406', to: 'errors#not_acceptable', via: :all, as: :not_acceptable_error
    match '/500', to: 'errors#internal_server_error', via: :all, as: :internal_server_error

    root 'home#index'
  end

end

app/views/shared/_administrator_menu.html.erb
<div class="col-lg-3">
  <div class="well sidebar-nav">
    <h3>Administration</h3>
    <ul class="nav nav-list">
      <% if current_page?(users_path) %>
        <li class="nav-header disabled-link">Users</li>
      <% else %>
        <li class="nav-header"><%= link_to "Users", users_path %></li>
      <% end %>
      <% if current_page?(companies_path) %>
        <li class="nav-header disabled-link">Companies</li>
      <% else %>
        <li class="nav-header"><%= link_to "Companies", companies_path %></li>
      <% end %>
      <% if current_page?(projects_path) %>
        <li class="nav-header disabled-link">Projects</li>
      <% else %>
        <li class="nav-header"><%= link_to "Projects", projects_path %></li>
      <% end %>
      <% if current_page?(tasks_path) %>
        <li class="nav-header disabled-link">Tasks</li>
      <% else %>
        <li class="nav-header"><%= link_to "Tasks", tasks_path %></li>
      <% end %>
    </ul>
  </div><!--/.well -->
</div><!--/div-->

app/views/shared/_errors.html.erb
<% if resource.errors.any? %>
  <%= ResourceMessageBuilder.build_html_errors(resource, 'errors.messages.not_saved',
       resource: resource.class.model_name.human.downcase) %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p>&copy; ProjectTimeTracker.com 2018</p>
</footer>

app/views/shared/_modal_dialog.html.erb
<div class='modal fade'>
  <div class='modal-dialog _modal-lg'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-hidden='true'>×</button>
        <span class='modal-title'></span>
      </div>
      <div class='modal-body _input-lg'></div>
      <div class='modal-footer'>
        <button type='button' class='btn btn-lg btn-cancel' data-dismiss='modal' />
        <button type='button' class='btn btn-lg btn-ok' />
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/shared/_pager.html.erb
<div class="apple_pagination">
  <div class="page_info">
    <%= pager_page_entries_info(resource) %>
  </div>
  <%= will_paginate resource, container: false %>
</div>